# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://slkrthika.github.io/
baseurl: /sustain/
title: mk
author: Chris Turner
description: Personal blog and resume
avatar: profile.png
email: sowmiyamks97@email.com
github: sowmiyamks97@gmail.com# username


# needed for travis-ci build
exclude: [vendor]
